spring.application.name=demo
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
server.error.whitelabel.enabled=false
server.error.include-stacktrace=never
server.error.include-message=always

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=skkr1924@gmail.com
spring.mail.password=pxih havz hgeu mqnh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-consolemanagement.endpoints.web.exposure.include=health,info

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always